# application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-python-app
  namespace: argocd
spec:
  destination:
    namespace: demoapp
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: my-python-app-chart
    repoURL: https://github.com/ronnirz4/KS8-Project.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
