apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-application-manager-binding
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: jenkins  # Jenkins namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-application-manager