apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: demoapp
data:
  index.html: |
    <html>
    <head>
    <title>Jenkins Project</title>
    </head>
    <body>
          <p style="text-align:center">Welcome to my Jenkins Project!</p>
          <p style="text-align:center">DevOps Course Nov 2023 - INT College</p>
          <p style="text-align:center">Created by Ron Letichevskiy</p>
          <p style="text-align:center">Today's Date and Time is: <span id='date-time'></span></p>
            <script>
              var dateAndTime = new Date();
                 document.getElementById('date-time').innerHTML=dateAndTime.toLocaleString();
            </script>
    </body>
    </html>
