apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: demo
data:
  index.html: |
    <html>
    <head><title>Welcome to nginx!</title></head>
    <body>
    <h1>Success! The nginx application is running!</h1>
    </body>
    </html>
