apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
  namespace: demoapp  # Replace with your namespace if different
spec:
  capacity:
    storage: 1Gi  # Size of the volume
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/nginx  # Path on the host where data will be stored

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc
  namespace: demoapp  # Replace with your namespace if different
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Requesting 1Gi of storage