apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2  # Number of replicas for the Nginx deployment
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: web-image-latest  # Ensure this image is correct and available
        ports:
        - containerPort: 8444
        volumeMounts:
        - name: static-content
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
      - name: static-content
        configMap:
          name: nginx-config  # Ensure this ConfigMap exists and contains the static content
1