apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "my-nginx-app.fullname" . }}-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: {{ .Values.pvc.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/nginx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-nginx-app.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
