apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-nginx-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "my-nginx-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "my-nginx-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "my-nginx-app.name" . }}
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: html-content
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: nginx-storage
          mountPath: /usr/share/nginx/html/storage
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.targetPort }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
      volumes:
      - name: nginx-config-volume
        configMap:
          name: {{ include "my-nginx-app.fullname" . }}-config
      - name: html-content
        configMap:
          name: {{ include "my-nginx-app.fullname" . }}-config
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: {{ include "my-nginx-app.fullname" . }}-pvc
      imagePullSecrets:
      - name: regcred
