replicaCount: 2

image:
  repository: ronn4/app-image
  tag: "last"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8443

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: my-python-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
namespace: demoapp  # Explicitly set the namespace
