apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins
  namespace: jenkins
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "services", "endpoints"]
  verbs: ["get", "list", "watch", "create", "delete", "update"]
1