apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-deployment-binding
  namespace: demoapp
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: jenkins
roleRef:
  kind: Role
  name: jenkins-deployment-manager
  apiGroup: rbac.authorization.k8s.io
